In [47]:
#ejercicio covid
import pandas as pd
#entendiendo lo que estoy haciendo en un ejemplo imaginario con datos mas simples para aclararme 
lista=[
    {"date":"blabla", "metadata":{"x":"y", "z":{"v":[]}}, "title":"A"},
    {"date":"bleble", "metadata":{"x":"y", "z":{"v":[]}}, "title":"B"}
]
# Leer de forma directa:
pd.DataFrame(lista)

date                    metadata title
0  blabla  {'x': 'y', 'z': {'v': []}}     A
1  bleble  {'x': 'y', 'z': {'v': []}}     B

In [48]:
#ejercicio covid 
# Leer la lista cuando está anidada dentro de diccionarios con un ejemplo más simple para aclararme 

item={
    "data":{
        "post": [
                  {"date":"blabla", "metadata":{"x":"y", "z":{"v":[]}}, "title":"A"},
                  {"date":"bleble", "metadata":{"x":"y", "z":{"v":[]}}, "title":"B"}
                ]
    }
}


df_x =pd.DataFrame(item)

post = df_x.data.post
pd.DataFrame(post)

date                    metadata title
0  blabla  {'x': 'y', 'z': {'v': []}}     A
1  bleble  {'x': 'y', 'z': {'v': []}}     B

In [49]:
#ejercicio nba18
#entendiendo lo que estoy haciendo con un ejemplo con valores más sencillos 
df1 = pd.DataFrame([{"a":1},{"a":2}])
df2 = pd.DataFrame([{"a":3},{"a":4}])
pd.concat([df1,df2], axis=0)#entendiendo lo que estoy haciendo con un ejemplo con valores más sencillos 
df1 = pd.DataFrame([{"a":1},{"a":2}])
df2 = pd.DataFrame([{"a":3},{"a":4}])
pd.concat([df1,df2], axis=0)

a
0  1
1  2
0  3
1  4

In [8]:
In [3]: np.<TAB>


SyntaxError: invalid syntax (<ipython-input-8-cafe7d82c7d0>, line 1)

In [9]:
In [4]: np?

Object `np` not found.


In [10]:
import numpy as np
np.random.seed(0)

In [11]:
x1 = np.zeros(6)  # One-dimensional array
x2 = np.ones((3, 4)) # Two-dimensional array
x3 = np.ones((3, 4, 5))  # Three-dimensional array

In [12]:
x1

array([0., 0., 0., 0., 0., 0.])

In [13]:
x2 = np.ones((3, 4)) #3 son las filas, y 4 son las columnas (3 filas, 4 columnas). este array es bidimensional. 
x2 #

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
x3 = np.ones((3, 4, 5))  # Three-dimensional array. 3 arrays, 4 filas, 5 columnas 

In [15]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


In [16]:
#Si está familiarizado con la indexación de lista estándar de Python, la indexación en NumPy le resultará bastante familiar. En una matriz unidimensional, se puede acceder al valor i-ésimo (contando desde cero) especificando el índice deseado entre corchetes, al igual que con las listas de Python:

In [17]:
x1

array([0., 0., 0., 0., 0., 0.])

In [18]:
x1[0]

0.0

In [19]:
x1[4]

0.0

In [20]:
#Values can also be modified using any of the above index notation:
#ha sustituido el valor del 0.0 (era 1.) por un 12
x2[0, 0] = 12
x2

array([[12.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [21]:
#Tenga en cuenta que, a diferencia de las listas de Python, las matrices NumPy tienen un tipo fijo. Esto significa, por ejemplo, que si intenta insertar un valor de punto flotante en una matriz entera, el valor se truncará silenciosamente. ¡No se deje sorprender por este comportamiento!

In [22]:
x1

array([0., 0., 0., 0., 0., 0.])

In [23]:
x1[0] = 3.14159  # this will be truncated! #preguntar a Clara 
x1

array([3.14159, 0.     , 0.     , 0.     , 0.     , 0.     ])

In [24]:
#Del mismo modo que podemos usar corchetes para acceder a elementos de matriz individuales, también podemos usarlos para acceder a submatrices con la notación de corte, marcada con el carácter de dos puntos (:). La sintaxis de segmentación NumPy sigue la de la lista estándar de Python; para acceder a un segmento de una matriz x, use esto: x [inicio: detener: paso]
#Si alguno de estos no está especificado, los valores predeterminados son inicio = 0, parada = tamaño de dimensión, paso = 1. Echaremos un vistazo al acceso a sub-matrices en una dimensión y en múltiples dimensiones.

In [25]:
x = np.arange(10)
print (np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [26]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [28]:
x[4:7]

array([4, 5, 6])

In [29]:
x[::2]  # every other element. Aqui saca los pares

array([0, 2, 4, 6, 8])

In [30]:
x[1::2]  # every other element, starting at index 1. saca los impares 

array([1, 3, 5, 7, 9])

In [31]:
x[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [32]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

In [33]:
#SLICING LA PARTE DE LA IZQUIERDA SON FILAS Y LA DE LA DERECHA SON COLUMNAS 

In [34]:
x2

array([[12.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [35]:
x2[:2, :3]  # two rows, three columns LA PARTE DE LA IZQUIERDA SON FILAS Y LA DE LA DERECHA SON COLUMNAS 

array([[12.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [36]:
x2[:3, ::2]  # all rows (filas), every other column

array([[12.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [37]:
x2

array([[12.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [38]:
x2

array([[12.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [39]:
x2[:3, ::1]  # all rows, every other column ME QUEDA POR ENTENDER ESTO 

array([[12.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [40]:
name="Jaime"
blabla="loquesea"
print("I am "+name+ ", and I like"+blabla+"at night")
print(f"I am {name} and I like {blabla} at night")

I am Jaime, and I likeloqueseaat night
I am Jaime and I like loquesea at night
